---
- name: disable selinux
  selinux: state=disabled

- name: Install repos
  copy: src="{{ item }}"
        dest=/etc/yum.repos.d/{{ item }}
  with_items:
    - rhel-server.repo
    - rhel-server-optional.repo

- name: upgrade all packages
  yum: name=* state=latest

- name: Install packages
  yum: name={{ item }}
  with_items:
      - rng-tools
      - firewalld
      - screen

# - name: Add second ethernet interface
#   command: nmcli connection  add type ethernet ifname eth1  con-name ethernet-eth1
#   when: not ansible_eth1.ipv4 is defined

- name: enable firewalld
  command: systemctl enable firewalld.service

- name: start firewalld
  command: systemctl restart firewalld.service

- name: disable selinux
  selinux: state=disabled

- name: patch rngd
  copy: src=rngd.service dest=/etc/systemd/system/rngd.service
  register: rngd

- name: reload systemd units
  command: systemctl daemon-reload
  when: rngd.changed

- name: Start the rngd service
  service: name=rngd enabled=yes state=started

- name: Set up authorized_keys for the deploy user
  authorized_key: user="{{ ansible_user_id }}"
                  key="{{ item }}"
  with_file:
    - public_keys/work.pub

- name: tty-less sudo
  sudo: yes
  lineinfile: dest=/etc/sudoers
              state=absent
              regexp='^Defaults(\s+)requiretty(\s*)$'
              validate='visudo -cf %s'

- name: Set server hostname
  sudo: yes
  hostname: name={{ hostname }}
